steps:
        - name: 'gcr.io/cloud-builders/docker'
          args: ['build', '-t', 'gcr.io/$PROJECT_ID/playlist-image', '.']
        - name: 'gcr.io/cloud-builders/docker'
          args: ['push', 'gcr.io/$PROJECT_ID/playlist-image']

images:
        - 'gcr.io/$PROJECT_ID/playlist-image'
